## Travis CI Integration

language: c

env:
 global:
  - EnableNuGetPackageRestore=true 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - nuget restore
  - xbuild EvolveSharp.sln
  - nunit-console Tests/UnitTests/bin/Debug/UnitTests.dll